namespace ChessLibrary.Engine;

public enum State
{
    NONE,
    IN_PROGRESS,
    WIN_WHITE,
    WIN_BLACK,
    DRAW_STALEMATE,
    DRAW_THREEFOLD_REPETITION,
    DRAW_FIFTY_MOVE_RULE,
    DRAW_INSUFFICIENT_MATERIAL
}