namespace ChessLibrary.Engine;

public enum State
{
    NONE,
    IN_PROGRESS,
    WIN_WHITE,
    WIN_BLACK,
    DRAW_STALEMATE,
    DRAW_THREEFOLD_REPETITION,
    DRAW_FIFTY_MOVE_RULE,
    DRAW_INSUFFICIENT_MATERIAL,
    WIN_WHITE_BLACK_ABORT,
    WIN_BLACK_WHITE_ABORT,
    WIN_WHITE_BLACK_RESIGN,
    WIN_BLACK_WHITE_RESIGN
}